### ISSUE TITLE
#18 リファクタリング：管理機能までのリファクタリングを行う

### ISSUE THREAD

**Issue by i-system-yaa999** [i-system-yaa999/rese_app#26]
・管理機能をある程度まとめた段階で、リファクタリングをおこない、ブランチ分けをしておく。

**Comment by AkiyoshiSatoshi** [comment]
優先順位をつけてリファクタリングを実施

* 主に見るところは、記述方法が統一されているか


1. Controller Eloquent DBクラス
2. Model 
3. Route
4. Blade
5. Middleware
6. その他のファイル←不要なコメントアウトやuse宣言を削除

所要時間 2時間
